# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython2.7
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.6
    - CONFIG=osx_c_compilerclangcxx_compilerclangxxpython3.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython2.7
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.6
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxxpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LMIFV/V5ycGlQW/ZEnr7zNN0pqujfYSyTKa2VaCpoID80mFFzkMdScQmDmBSAaK0CTw3O0fuInJWEz8LBzdHgn7qbV1qwnOQAtxmoftm5qkyzJsFmtVIezSRMUMPCaAsem2LrG0zyhG3uKzrYBEhhseVPQgRmQpXWPyw+qgW14+2hJEFHIMLs9nCkLr7xmnBd07Qy2QZPKUheCvdwNFu7SGYlcloTrVvM5lpTAg7CU5jaibFmfMRZAShRl0hJCwvj3L7/MMl7NXCXD6sFg3fCvAwwIXjHyOIiVfYS4QxqKDTp6jV0iSAj3FC1SXXNSjFpSZ09qeL34peFHlVYSw0L2ToQMLamiR4BoF0Dp5EfZWfL5v4aTjYBNLeMqArC1AHkuakArU+xzDZGMfxks5iIyhoac7K+EvM6i3IWxcUVpFbAw91ocunRt+3xiLqth8p0prASusaqNFUPvXcEV64A3EBdzxCIOpHSyqttwvGCQh7p2iUcMw/tpYjvfCekhow3kPve2+h5bkmg03eXs5XIS0M4Vzt3t5z4+0huJiQRJzQ7q6GAaiNKOVAZiNkH0Id11F2KdTAUrH50ZPD0TFf4GBzT0mfyJOsITmyzCWKka1BVB2upzX/mKIsLEUi1XgOYTp+BxkpFhEWJX2B0AE4h63eFKL+kWaFRL32kg7yQCg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
