travis:
  secure:
    BINSTAR_TOKEN: LMIFV/V5ycGlQW/ZEnr7zNN0pqujfYSyTKa2VaCpoID80mFFzkMdScQmDmBSAaK0CTw3O0fuInJWEz8LBzdHgn7qbV1qwnOQAtxmoftm5qkyzJsFmtVIezSRMUMPCaAsem2LrG0zyhG3uKzrYBEhhseVPQgRmQpXWPyw+qgW14+2hJEFHIMLs9nCkLr7xmnBd07Qy2QZPKUheCvdwNFu7SGYlcloTrVvM5lpTAg7CU5jaibFmfMRZAShRl0hJCwvj3L7/MMl7NXCXD6sFg3fCvAwwIXjHyOIiVfYS4QxqKDTp6jV0iSAj3FC1SXXNSjFpSZ09qeL34peFHlVYSw0L2ToQMLamiR4BoF0Dp5EfZWfL5v4aTjYBNLeMqArC1AHkuakArU+xzDZGMfxks5iIyhoac7K+EvM6i3IWxcUVpFbAw91ocunRt+3xiLqth8p0prASusaqNFUPvXcEV64A3EBdzxCIOpHSyqttwvGCQh7p2iUcMw/tpYjvfCekhow3kPve2+h5bkmg03eXs5XIS0M4Vzt3t5z4+0huJiQRJzQ7q6GAaiNKOVAZiNkH0Id11F2KdTAUrH50ZPD0TFf4GBzT0mfyJOsITmyzCWKka1BVB2upzX/mKIsLEUi1XgOYTp+BxkpFhEWJX2B0AE4h63eFKL+kWaFRL32kg7yQCg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
